version: '3'
services:

  db:
    image: hk2281/alex_bd:latest
    networks:
      localMad:
        aliases:
          - mysql

  backend:
    image: hk2281/nest:latest
    depends_on:
      db:
        condition: service_started
    networks:
      - localMad
    ports:
      - "8080:8080"
    restart: always
  
  frontend:
    image: hk2281/angular_v1_nginx:latest
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - localMad
    restart: always

networks:
  localMad:
    driver: bridge

